### ISSUE TITLE
Should we make the admin header and title be configurable for example of grappelli?

### ISSUE THREAD

**Issue by zchking** [django-admin-bootstrap/django-admin-bootstrap#69]
```
  #settings.py

  ADMIN_TITLE = "Django Admin"

  ADMIN_BRAND_TITLE = "Django Admin"

  ......
```
  
As django 1.7 + has the feature of customizing the AdminSite conveniently,should we add the feature such as set the admin title in settings.py

**Comment by douglasmiranda** [comment]
I will think about this, but it's a good idea indeed.

**Comment by michaelkuty** [comment]
here is my simple example how you can propagate to settings, but i think is not relevant for this project, you want you can write these lines and that's it.


	from django.conf import settings
	from django.contrib import admin
	from django.contrib.admin.sites import AdminSite


	class LeonardoAdminSite(AdminSite):

	    site_header = getattr(settings, "SITE_HEADER", "Leonardo administration")

	    site_title = getattr(settings, "SITE_TITLE", "Leonardo site admin")

	    def get_urls(self):
    
	        # connect all admin members

	        self._registry.update(admin.site._registry)

	        return super(LeonardoAdminSite, self).get_urls()

	leonardo_admin = LeonardoAdminSite(name="admin")

**Comment by nanuxbe** [comment]
Isn't this a bit of an overkill?

Setting the site title and header since 1.7 simply requires you to add those 2 lines at the end ``urls.py``

    admin.site.site_header = "Leonardo administration"
    admin.site.site_title = "Leonardo site admin"

Also since Django 1.7 ``auto_discover`` is not run from ``urls.py`` anymore but from ``AppConfig`` so you cannot simply tell people to replace ``admin.auto_discover()`` with ``bootstrap_admin.auto_discover()``. This would mean that
 * if this feature is intended for "the general public", this would mean creating and ``AdminSite`` subclass in here and have users replace ``django.contrib.admin`` with ``django.contrib.admin.apps.SimpleAdminConfig`` in ``INSTALLED APPS`` (since ``django.contrib.admin`` still needs to be present in order to provide some templates and static files it cannot simply be removed) in order to prevent the regular admin to register all the model admins or find a way to monkey-patch ``django.contrib.admin.site.register`` to have it register the models with bootstrap_admin instead of the regular admin or both.
 * if this is only intended for people who write custom admins, well, they are writing a custom admin already so they probably know how to do it themselves.

So, if you think this is actually something that most people will want to do, I'm wondering if it wouldn't be better/simpler to just put it somewhere in the docs or a FAQ?

**Comment by michaelkuty** [comment]
emma thanks, for your suggestion, i forgot, that is django 1.7+ :D you are absolutly right

**Comment by douglasmiranda** [comment]
Yes, for now we put on README.
